### ISSUE TITLE
Would scraper produce citation?

### ISSUE THREAD

**Issue by whaleloops** [HanjieChen/ChallengeClinicalQA#1]
Would this code also scrape In-text Citations in the discussion section?

For example: multiple citations here https://jamanetwork.com/journals/jamaotolaryngology/fullarticle/2815482

**Comment by ZhouxiangFang** [comment]
Thank you for your question! 

It wouldn't since the citations are not necessary for our tasks. 

However, you may edit the scraper to crawl the data that you need. 

You may refer to the document https://beautiful-soup-4.readthedocs.io/en/latest/.
