### ISSUE TITLE
Having a hard time understanding JSON and CSV format

### ISSUE THREAD

**Issue by SamuelSchmidgall** [HanjieChen/ChallengeClinicalQA#2]
Hello,

Could you provide a processing script for loading the medbullets JSON/CSV files?

Sam

**Comment by ZhouxiangFang** [comment]
Hi Sam,

We recommend using **pandas** to read and process the json/csv file. 

You may refer to https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html and https://pandas.pydata.org/docs/reference/api/pandas.read_json.html
